sudo: required
language: java
jdk:
  - oraclejdk7
#  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

services:
  - docker

addons:
  hosts:
    - petstore.swagger.io

before_install:
  # required when sudo: required for the Ruby petstore tests
  - gem install bundler
  - npm install -g typescript
  - sudo pip install virtualenv
  # to run petstore server locally via docker
  - docker pull swaggerapi/petstore
  - docker run -d -e SWAGGER_HOST=http://petstore.swagger.io -e SWAGGER_BASE_PATH=/v2 -p 80:8080 swaggerapi/petstore
  - docker ps -a
  # show host table to confirm petstore.swagger.io is mapped to localhost
  - cat /etc/hosts

install: true

script:
  - mvn verify -Psamples
  - if [ $DOCKER_HUB_USERNAME ]; then docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD && docker build -t $DOCKER_IMAGE_NAME ./modules/swagger-generator && if [ ! -z "$TRAVIS_TAG" ]; then docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$TRAVIS_TAG; fi && docker push $DOCKER_IMAGE_NAME; fi

after_success:
- "./.travis/before-deploy.sh"
- "./.travis/deploy.sh"

env:
  matrix:
  - DOCKER_IMAGE_NAME=swaggerapi/swagger-generator
  global:
  - secure: b7DP6A8VewHa6c6NbPtRT+oFgC64iagj27QTGyMwMG/VxewYcyhakZT9BEsR8IqtoMzg9WZFPpTPgTRmNt6xdmpgzJldbYURUqxhPAAKG2shZBJPP8T6ATJKIf1fwv4GrMCxWGwAhmPT6HBqeiQ0UfRrGd8gC0p1yHPfoo6Q5um6RYVpX/cG2amJUA3nMgiLRGrzIP9gaInKg3P1CWz3fVvrTJ4Oh/VZjmvoOj46NTRMk/vUM+JLPq4ZNcL2iIZLiakYsD3Lh8YQN7GBZxWbZeY6owLh5FejNhAHS1eojkTpXiKmE898xY/N3nhkppOdjR13MaqAgQIIC2RR6YskSt7RKRolvTQwgAbIUJ/xucHvWks0TbsJPimBx4Jjyeet4kl3WhKHdexFOzDFKmL5k5E9K3I775j3njIZ29kKmoVeyv0GDQd262UpZecqVh8ZPcyRHwxxu5yixb+HbKsiIxuWXrlzeAoDGCBJ3qUqu6fOMR4f4p5Fzey6tF8MWrz2+8NhcItLCeva8z57jSwGtsinb4NS7Yhw7QxxbvDjr8weA/Eq3Xa8pMaWHuyqYenDQM6dxkPxkaE7n8HmipHZSecirbcX4YttDpQppXIGeH2eIpp99BAlIsBoyABI3S03fsxEV9PGe2Zeu+LYJJJGFiOO9dgaoBmrGnPcs5ypkco=
  - secure: S2fxmCnx8TbsiRYKwbejwTZlyhN2QTpwpnn4ycDXlIcrqzCePbPzA9EzFOm9oz+9hNGjExvgZ6JxpZbZh+DSPkMo0MS9u6Ob1Del2yxTTwmnohhu0MzfyH/Q9pSQHYDgYvjVg10cU7EmzTYqpDicBMEi825+Ip9SGgUhJ5HTIv9jXvWKasie0YfPlex2ltT2y4xzJAw9n2RX3i/hGJX0HapeOyc4vpXeXjNFrxjRA/87okH02ONKT0bUy4iRi84CdwlBqjwf3IkRkay75hx0Bs/l13HvG0gzAlpA9cZgK67mliC61RCVslAasRL7Yq9h00PlkJEjXV87GCIjZXJvJqzDsGULbelc6LSzAW/+VmSBqWw0pLLudPKBl/x+XRR5mfiGF3zh1hVB6cm/OMgCLmpmEpNOXvsVKX0QQ448cPCM2jJ4w0feSKlODaSoKq/9decqYFH4La3b0dXf7d3RAJ0Gy24E9X+yvFjYhITYJdaM1W2AQeBq1tubNQGaodj0I4kcoy7aqWECxU1o1LhwJENrjHtauOd8migk6SRyoBZ6YY06cqpnHv2sgycIaPP54aonl2Fl7Nhlpk0ijRFy4tGnS9FAH7rhPJBG7egpMBYCwvos5WMYh82epJDDt+1qSTgolDofdM9YWpccaGV+ivHWUHmRPijh5K4pvLZ+D0M=
  - secure: fixOpwmg0sK46qyZnIS2xqEFVxtL5HEztGyfVUYox8472h5WB+btjZfMEEL9FhHQg0aVY+MFQVEQ7UNlGg76lhr+UwHKTanwL/wnoxgJk63stdPTxbQt45y4LWxc5J/nvKHjGvOBa3QHoHjELWtkmPEEDgJQdowDJxsuvTVLgeeclSCchL0ZuKNOcYg4BUXoymVvRQEvQGys0TKdlPIxg8lFo1HKDZsD3kIGxVjNcDG/88+SVvUKFZ13xZLUxQ/sTryQ0bBWhgiOqpbM0W95//KgMeelHDGqLZXZu2R7n51U4b17MfMs8i6aUxr//2fMCgFWJhWH1rFcpfTpbjHLtfkUxfBouXYyph0pp6BLB2Uw+Vx9k5Q0ROwN92uojCcLBWi6L2jzVtK5tIQJScaTLijaD1yD10Ai1IEyQtIHcDGK9XCzv2OukswfQ7qJ5cJek5lXQ4FLzpuyeTpZ2QhQmdsZcQgOjh+1OZCybfOUhGqki4xbQPTYJCibEBw6VVfB9x+ENmbiYHyeIi1o/De7IPQhtY36N9wwkDhJR4xeWeRjF8w0wU+pcNSGwmzSKXCTITFgBOUWHsnHmfSZ9tov9anYESBEGIDdcjKjglosTOVffhtkTwC85MASnmEyg27bhqdeDrYe3mIrWqxn2MPY/XuqVXUG03kqL2sP3VtkS0k=
  - secure: HW0e35Zk/tEYRurQsRmcgVWNdGI76GcfSZ+jzHkW5mj7dM5E57vnT3Z9gsBxV90ssRgbqH/+o/lHdKsaSEjs3AHItziHYIcDQ4oEYof6NU82Y9RJsaEcYmnSDghkbM8EbWbl5GaXhXdlSkJSbltDpgiDQuh/n+U3SDa+Cjr+kiSPYcifNZNlekKogOLSNuOvf6tleDoBPav3YE5YIxCpIysgDbsyz2lal4FY7xNwMvT9xZvHSqViGx3qGOjZ3+bRlD8UUMrR2Sj7YKJB9U48SGmw5mE/K28u+HSW5dlxe38gD6ZE1T1LPbdMGIjG0ioSkWHmhFEigLvYdFNXXGSUVn43NCItyRh18oxbm4ckHqyf7p56ydi9nQST3BpMuUNHwyiEl0vku6FT1/EeMj05JBqoJRrkyLx13RgK3KDnLa4EJGdovprcH2FZp/TR1aTWb66pE0d1xAYadiPqfqk4bEbibs4ZLcwJg/3kviIVlMsk+QgyCwOolU539CLS+VKjwmk2UEPRzm64tVF089QqHNNC6uUbXi1+tp4UVbu66c9/F1GeTXfIHuTg98rbWR1vTKATLRmbIMwH22AymusZQZMduCmSKUO05MI4Ol8Bn5p3NTTKwOq0LJC1xDAunqN4oF/wYPoQ/O4zCjSHdfvNi4CG7UGA2P38y1UygaWWh7Q=
